### ISSUE TITLE
Traffic Light - Pass/Failure

### ISSUE THREAD

**Issue by csmith17-chwy** [open-automation/switch-sql-query#2]
Would be helpful to have a traffic light connection out of the switch-sql-query script so that if a file fails to query it can be directed appropriately.

<img width="604" alt="screen shot 2016-08-29 at 11 32 49 am" src="https://cloud.githubusercontent.com/assets/11652313/18057033/625be764-6ddc-11e6-93b0-4316d91ff2d3.png">

Thanks

**Comment by dominickp** [comment]
Complete in 17675d2e06dac9e437ba2cd2ba6b889aa66be97e
